# Generated by Django 4.1.3 on 2023-04-05 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_investor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='full_name',
        ),
    ]
